import { chromium } from 'playwright'
console.log('launching...')
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--no-sandbox','--disable-dev-shm-usage'] })
console.log('launched')
const page = await browser.newPage({ viewport: { width: 414, height: 896 } })
page.on('pageerror', e => console.log('PAGEERROR:', e.message))
page.on('console', m => console.log('console:', m.type(), m.text().slice(0,200)))
await page.goto('http://localhost:4173/', { waitUntil: 'domcontentloaded', timeout: 15000 })
console.log('loaded, title=', await page.title())
await page.waitForTimeout(1500)
console.log('body length:', (await page.content()).length)
console.log('has local-mode btn:', await page.locator('[data-testid=local-mode]').count())
await page.screenshot({ path: '/home/claude/fa/shots/debug.png' })
console.log('screenshot done')
await browser.close()
