// GENERATED by scripts/art-hashes.mjs - do not edit.
//
// Content hash per art file, so replacing a picture under the same name still
// reaches browsers that already cached the old one. See the script for why this
// exists at all.
export const ART_HASHES: Record<string, string> = {
  'adrian.webp': 'e8e043cc',
  'amanda.webp': 'c76d230e',
  'bry.webp': '52bf912d',
  'carlitos.webp': '71598ad4',
  'chichi.webp': '965ea93d',
  'chris.webp': 'c0c411b1',
  'dainese.webp': '086d791c',
  'dorian.webp': '44fa935c',
  'elias.webp': '2e597baf',
  'family.webp': 'b4de5b40',
  'gabby.webp': '1bd3b766',
  'grandma.webp': '9e93466d',
  'grandpa.webp': '06b41f20',
  'hoza.webp': '78b62385',
  'jay.webp': '73961b7d',
  'justin.webp': 'e6c1e6a8',
  'kevin.webp': '9cbea609',
  'larry.webp': '9508aea5',
  'manny.webp': '53abefdc',
  'mikeymoe.webp': '61939fa2',
  'nani.webp': 'a1fbd95c',
  'titibibi.webp': 'ee4053b6',
  'titibum.webp': '2f975ce0',
  'xavi.webp': 'acd5a53e',
}

/** Art URL for a filename from a card definition, cache-busted by content. */
export function artUrl(file: string): string {
  const h = ART_HASHES[file]
  return `${import.meta.env.BASE_URL}art/${file}${h ? `?v=${h}` : ''}`
}
