// Fingerprints every file in public/art so a replaced picture actually reaches
// the people who already have the old one.
//
// Vite hashes the JS and the CSS, but anything in public/ is copied out
// verbatim under the name it went in with. Replace jay.webp with a new jay.webp
// and GitHub Pages serves it with the same URL, so every browser and every
// intermediate cache that has seen it keeps showing the old face - forever, as
// far as the player is concerned. Nothing about that is visible to whoever
// uploaded the new art: it looks right locally, it looks right in the repo, and
// it is wrong on the phone in your hand.
//
// So: hash the bytes, write the map, and let the app ask for art/jay.webp?v=<8
// characters of sha1>. New bytes, new URL, no refactor of how cards name their
// art, and a file that has not changed keeps its URL and stays cached.
import { createHash } from 'node:crypto'
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const DIR = 'public/art'
const OUT = 'src/ui/artHashes.ts'

const files = readdirSync(DIR).filter((f) => /\.(webp|png|jpe?g|gif|svg)$/i.test(f)).sort()
const entries = files.map((f) => {
  const hash = createHash('sha1').update(readFileSync(join(DIR, f))).digest('hex').slice(0, 8)
  return `  '${f}': '${hash}',`
})

writeFileSync(OUT, `// GENERATED by scripts/art-hashes.mjs - do not edit.
//
// Content hash per art file, so replacing a picture under the same name still
// reaches browsers that already cached the old one. See the script for why this
// exists at all.
export const ART_HASHES: Record<string, string> = {
${entries.join('\n')}
}

/** Art URL for a filename from a card definition, cache-busted by content. */
export function artUrl(file: string): string {
  const h = ART_HASHES[file]
  return \`\${import.meta.env.BASE_URL}art/\${file}\${h ? \`?v=\${h}\` : ''}\`
}
`)
console.log(`wrote ${OUT} for ${files.length} art files`)
